// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquyuii5WXgxh7tvt7wjY1yiJ_kSn6qPo',
    appId: '1:916337678378:web:396c3344554d156b410b53',
    messagingSenderId: '916337678378',
    projectId: 'calmspace-29937',
    authDomain: 'calmspace-29937.firebaseapp.com',
    storageBucket: 'calmspace-29937.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqbjLZh1Bl6Kt9DenVZ3I8E3mgxU1YCk',
    appId: '1:916337678378:android:b32b6527bd427cc1410b53',
    messagingSenderId: '916337678378',
    projectId: 'calmspace-29937',
    storageBucket: 'calmspace-29937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2QJlLL7jB1fFmuaI-ew7GMgpZvmQ3Bk',
    appId: '1:916337678378:ios:7ebac4cae581f04b410b53',
    messagingSenderId: '916337678378',
    projectId: 'calmspace-29937',
    storageBucket: 'calmspace-29937.firebasestorage.app',
    iosBundleId: 'com.example.calmSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2QJlLL7jB1fFmuaI-ew7GMgpZvmQ3Bk',
    appId: '1:916337678378:ios:7ebac4cae581f04b410b53',
    messagingSenderId: '916337678378',
    projectId: 'calmspace-29937',
    storageBucket: 'calmspace-29937.firebasestorage.app',
    iosBundleId: 'com.example.calmSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquyuii5WXgxh7tvt7wjY1yiJ_kSn6qPo',
    appId: '1:916337678378:web:ad798670091d8250410b53',
    messagingSenderId: '916337678378',
    projectId: 'calmspace-29937',
    authDomain: 'calmspace-29937.firebaseapp.com',
    storageBucket: 'calmspace-29937.firebasestorage.app',
  );
}
